spring.datasource.url=jdbc:postgresql://localhost:5432/schemaguard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=false

jwt.secret=Sch3m@Gu4rd#S3cr3t!K3y$2024%Ultra$Secure&Token@Key!